### ISSUE TITLE
Why actor needs to be conditional on ID？

### ISSUE THREAD

**Issue by wjh-scut** [ffelten/MASAC#1]
Hello, I would like to ask, since it is a scene of homogeneous agents, why does the shared actor need to use ID as a condition? Is it ok if you don't use the ID as part of the state?

**Comment by ffelten** [comment]
Hello,

Depends on what you put in the state of the agent. For example, I used MASAC to learn behaviors for drones formation: https://github.com/ffelten/CrazyRL

In this example, instead of feeding the coordinates of other drones to each agent, I just feed the ID, and the drones knows where it should do its circle. 

We could imagine avoiding the need to condition on the ID by feeding the coordinates of the other agents so that the agent is able to understand it should go to a circle that is not assigned yet or something. But there must be a way for each agent to identify its role in the multi-agent system.

**Comment by wjh-scut** [comment]
Thanks for your reply, I understand now. By the way, your research is very interesting, I am also researching the application of MARL on Multi-UAVs, looking forward to seeing your continuous updates!

**Comment by ffelten** [comment]
Thanks! If you have more questions, don't hesitate. You can also ping me on discord: ffelten#1661
